---
#collections:
 # - name: kubernetes.core
  #ansible-galaxy collection install kubernetes.core
- name: Get current OpenShift user and list pods
  hosts: localhost
  gather_facts: false
  vars:
    ocp_api_host: "api.bsbs.bsbs:6443"
    ocp_token: "FAKETOKENrQFD2-sDq4BeaQdSAH-uUyfAfMBAejaBukUwRAXqHE4"
    namespace: "kbc-jwt"  # replace this with the actual namespace
  tasks:
    - name: Get current user info from OCP API
      uri:
        url: "https://{{ ocp_api_host }}/apis/user.openshift.io/v1/users/~"
        method: GET
        headers:
          Authorization: "Bearer {{ ocp_token }}"
        return_content: true
        validate_certs: false
      register: response

    - name: Debug current OpenShift user
      debug:
        var: response.json

    - name: Get all pods in a namespace
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: "{{ namespace }}"
        api_key: "{{ ocp_token }}"
        host: "https://{{ ocp_api_host }}"
        verify_ssl: no
      register: pod_list

    - name: Display pod names
      debug:
        msg: "{{ item.metadata.name }}"
      loop: "{{ pod_list.resources }}"
