---
#collections:
 # - name: kubernetes.core
  #ansible-galaxy collection install kubernetes.core
- name: Get current OpenShift user
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get current user info from OCP API
      uri:
        url: "https://api.emeacluster.emea-devops-lab.cybr:6443/apis/user.openshift.io/v1/users/~"
        method: GET
        headers:
          Authorization: "Bearer sha256~rQFD2-sDq4BeaQdSAH-uUyfAfMBAejaBukUwRAXqHE4"
        return_content: true
        validate_certs: false
      register: response

    - debug:
        var: response.json

    - name: Get all pods in a namespace
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: "{{ namespace }}"
      api_key: "{{ ocp_token }}"
      host: "https://{{ ocp_api_host }}"
      verify_ssl: no
    register: pod_list

    - name: Display pod names
    debug:
      msg: "{{ item.metadata.name }}"
    loop: "{{ pod_list.resources }}"
